# Generated by Django 3.2.21 on 2023-09-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
