# Generated by Django 3.2.21 on 2023-09-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_mymodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='phone',
        ),
    ]
