# Generated by Django 3.2.21 on 2023-09-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_mymodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
