# Generated by Django 3.2.21 on 2023-09-14 17:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_mymodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=10, region=None),
        ),
    ]
